### ISSUE TITLE
A few functions missing from std namespace

### ISSUE THREAD

**Issue by chaoren** [android-ndk/ndk#82]
NDK version 12.0.2763256-beta1

```
$ cat test.cpp
#include <cmath>
#include <string>

int main() {
        (void) std::nextafter(0.0, 0.0);
        (void) std::round(0.0);
        std::log2(0.0);
        std::to_string(0);
}
$ ~/Android/toolchains/arm/bin/arm-linux-androideabi-clang++ -std=c++11 test.cpp
test.cpp:5:9: error: no member named 'nextafter' in namespace 'std'; did you mean simply 'nextafter'?
        (void) std::nextafter(0.0, 0.0);
               ^~~~~~~~~~~~~~
               nextafter
.../Android/toolchains/arm/bin/../sysroot/usr/include/math.h:245:8: note:
      'nextafter' declared here
double  nextafter(double, double) __NDK_FPABI_MATH__;
        ^
test.cpp:6:9: error: no member named 'round' in namespace 'std'; did you mean simply 'round'?
        (void) std::round(0.0);
               ^~~~~~~~~~
               round
.../Android/toolchains/arm/bin/../sysroot/usr/include/math.h:274:8: note:
      'round' declared here
double  round(double) __NDK_FPABI_MATH__;
        ^
test.cpp:7:2: error: no member named 'log2' in namespace 'std'; did you mean simply 'log2'?
        std::log2(0.0);
        ^~~~~~~~~
        log2
.../Android/toolchains/arm/bin/../sysroot/usr/include/math.h:240:8: note:
      'log2' declared here
double  log2(double) __NDK_FPABI_MATH__;
        ^
test.cpp:8:7: error: no member named 'to_string' in namespace 'std'
        std::to_string(0);
        ~~~~~^
4 errors generated.
```

http://en.cppreference.com/w/cpp/numeric/math/nextafter
http://en.cppreference.com/w/cpp/numeric/math/round
http://en.cppreference.com/w/cpp/numeric/math/log2
http://en.cppreference.com/w/cpp/string/basic_string/to_string

Standalone toolchain created with:

```
$ ./build/tools/make-standalone-toolchain.sh --platform=android-24 --arch=arm --use-llvm --install-dir=$HOME/Android/toolchains/arm
```

**Comment by chaoren** [comment]
There's probably a lot more. These are just the few I ran into.

**Comment by DanAlbert** [comment]
Sounds like not a regression, so actually r13 since the solution is going to take quite a bit of effort to fix thanks to autoconf being bad: https://code.google.com/p/android/issues/detail?id=82734

**Comment by zergtmn** [comment]
std::to_string is still missing in r13 beta1.

**Comment by tzutalin** [comment]
Hope std::to_strong-arm into r13

**Comment by DanAlbert** [comment]
It will not be in r13. The "fix" for this is that we're working on libc++ so gnustl becomes unnecessary. r14 is probably when that will be done. It's been the entire focus of r13, but there are a lot of intermediate tasks to getting it done.

**Comment by DanAlbert** [comment]
Getting libc++ into shape depends on unified headers, which are going to take all of the r14 cycle.

**Comment by kangjoni76** [comment]
@DanAlbert, sorry for spam, I want to know what feature of libc++_shared that is still missing to solve stack unwinding problem for either ice cream sandwich and gingerbread?

**Comment by DanAlbert** [comment]
@kangjoni76: Are you referring to the exception handling issues mentioned in the [Known Issues] for the last few releases? libc++ has more issues than that (see the warnings in the libc++ section of [our docs]).

As for the exception unwinding issues, the KI list looks like it was actually more general than the problem really is. It seems to affect only armeabi (doesn't affect arm7): https://android.googlesource.com/platform/ndk/+/master/tests/device/libcxx-unwind/test_config.py. Whether or not it still affects ICS is unknown, since I don't have an ICS device handy atm.

[Known Issues]: https://github.com/android-ndk/ndk/wiki/Changelog-r13#known-issues
[our docs]: https://developer.android.com/ndk/guides/cpp-support.html#cs

**Comment by kangjoni76** [comment]
yes I was referring to that case. I couldn't move on from exiting r10e release. It's still unclear to me, perhaps shouldn't official wiki to provide complete tescase exception handling progress report on  ARM especially for libc++_shared part, so that we could better know edge case part about this. https://developer.android.com/ndk/guides/cpp-support.html

**Comment by DanAlbert** [comment]
Exception unwinding was broken in r10e too... In fact, it was much worse.

Actually, digging in to this to verify that it was broken in r10e, it looks like this was fixed some time during the development of r12 (the test was added early in r12). There was a misconfiguration in the test that was causing it to be skipped rather than reporting that a known failure was passing, which is why it didn't get removed from the known issues list.

I'll get the changelog updated to reflect this.

**Comment by kangjoni76** [comment]
I'm still using libstdc++_shared at r10e, well using qt5 5.6 qml is not c++ exception heavy code yet. But the Google project that is grpc in which I had filed an issue https://github.com/grpc/grpc/issues/7898 still showstopper. They use many exception code. But thank you very much anyway for considering this.

**Comment by Thooms** [comment]
Hello, I ran into the very same bug for the function `snprintf` (which is supposed to be part of `std::` too) :) I'm on NDK version `13.1.3345770`.

**Comment by sliu012** [comment]
hi all,
I resolved the issues w.r.t. "'stoi' is not a member of 'std'" ,"stddef.h: No such file or directory"  
with the following steps:
1. enter the directory "android-ndk-r13b/build/tools"
2. then get the toolchain using:
sh make-standalone-toolchain.sh --arch=arm \
--platform=android-16 \
--install-dir=/somewhere/Android-16_Toolchain  \
--stl=libc++

3. compile your c++11 .cpp file using the following command:
/somewhere/Android-16_Toolchain/bin/arm-linux-androideabi-g++ -std=c++11 \
-isystem /somewhere/Android-16_Toolchain/include/c++/4.9.x/ 
 -o test test.cpp -lc++_shared

**Comment by DanAlbert** [comment]
Work for O ate all of r15's time, so this is going to have to wait for r16.

**Comment by DanAlbert** [comment]
Okay, as of r16 libc++ is in good enough shape to recommend it. If you need these functions, migrate over to libc++.

Thanks for bearing with us on this one. Sorry it took so long!

**Comment by rcdailey** [comment]
@DanAlbert I get crashes in boost (something in their `boost::exception` code) with r15b LLVM STL that I do not get using GNU STL. I tried debugging it for a few hours but without proper backtraces in tombstones and inability to use ndk-gdb with CMake builds, I couldn't get very far. I'll try with r16 and see if it makes a difference. I'm hoping it was due to libc++ issues. Since you recommend it in r16 should be worth another try...

**Comment by scottbouma** [comment]
Sorry for the newbie request: how do I actually download the r16 beta?  Thanks!

**Comment by enh** [comment]
right now, r16 is only available as a continuous build: https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md

when there's an "official" beta, it'll be available here: https://github.com/android-ndk/ndk/wiki

**Comment by aschrijver** [comment]
With latest canary build I still have issues that seem related to this issue. See: https://github.com/nodejs/node/issues/14771

**Comment by DanAlbert** [comment]
You're still using gnustl in that. See https://github.com/android-ndk/ndk/issues/82#issuecomment-236979264

**Comment by aschrijver** [comment]
Thanks @DanAlbert !
It is not fully clear how I can configure that. I tried adding `--stl=libc++` to the toolchain cmd in `android-configure` but that does not do it.

**Comment by aschrijver** [comment]
FYI This issue is the only blocker still remaining to upgrading V2J8 to Node 8.1.2: https://github.com/eclipsesource/J2V8/pull/327#issuecomment-322931893

**Comment by matiwinnetou** [comment]
@aschrijver : J2V8... :)

**Comment by drywolf** [comment]
To elaborate a little bit more ... J2V8 is currently using [android-gcc-toolchain](https://github.com/sjitech/android-gcc-toolchain) to run its Android build. I had a quick look into the [NDK toolchain documentation](https://developer.android.com/ndk/guides/standalone_toolchain.html) and other sources, and I think I read somewhere that the `--stl=libc++` option is not supported when using GCC for the compiler. My next step now would be to try and use `make_standalone_toolchain.py` to get a Clang-based build running without the use of android-gcc-toolchain altogether.

However, I am unable to find a part of the documentation specifically saying that when using Clang of the Android NDK that then the libc++ problems will all go away. What I mean to say is that it is unclear to me if linking against the libc++ is fully implemented & supported for the Android NDK at this point.

I will post my results here once I'm further down this road.

**Comment by rcdailey** [comment]
According to other posts I've read, r16 will be when libc++ is "ready"

**Comment by aschrijver** [comment]
I think you will have to try with the canary build, like I did for `8.3.0`: https://github.com/nodejs/node/issues/14783#issuecomment-322022392

**Comment by drywolf** [comment]
Thanks for the hints

**Comment by DanAlbert** [comment]
Can we move this discussion to a nodejs bug please? This bug is fixed. Any issues nodejs is having are not related to this bug.

Feel free to CC me on the bugs. I'm happy to help, just don't want to bog down this thread with unrelated conversation.

**Comment by ec1oud** [comment]
What about log2, is it included yet?

**Comment by enh** [comment]
the test.cpp in the original example builds fine with NDK r17.
